### ISSUE TITLE
Issue with Infinite Spire's Portal Room Quest

### ISSUE THREAD

**Issue by spikeof2010** [The-Evil-Pickle/Replay-the-Spire#101]
For whatever reason, I keep crashing when I return from the quest screen from Blank's Infinite Spire Quest Log screen, I keep crashing after entering a portal room. I'm not sure which github I should be reporting this too, but I'm dropping this error log here anyway.

`
07:39:34.610 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: QUEST_LOG_SCREEN
07:39:34.628 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:230) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:53) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.mod.replay.rooms.TeleportRoom.update(TeleportRoom.java:63) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2528) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
`

**Comment by erasels** [comment]
```
INFO infinitespire.InfiniteSpire> I am being removed:Visit a Portal room.
12:48:02.886 INFO infinitespire.InfiniteSpire> I am giving my reward! 1 : Visit a Portal room.
12:48:03.694 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: QUEST_LOG_SCREEN
Exception: java.lang.NullPointerException
12:48:03.704 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
    at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:236) ~[?:?]
    at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:53) ~[SlayTheSpire.jar:?]
    at com.megacrit.cardcrawl.mod.replay.rooms.TeleportRoom.update(TeleportRoom.java:63) ~[ReplayTheSpireMod.jar:?]
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2531) ~[?:?]
```

I think there's an incompatibility between infiniteSpire and ReplayTheSpire. I crashed when I took the quest reward for entering a portal and returning to the screen after pressing enter the portal.
---
```
Loading into: 1,9
com.megacrit.cardcrawl.mod.replay.rooms.TeleportRoom
com.megacrit.cardcrawl.rooms.EmptyRoom
12:51:15.341 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
Exception: java.lang.NullPointerException
12:51:15.343 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2295) ~[?:?]
    at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:581) ~[?:?]
    at com.megacrit.cardcrawl.dungeons.TheCity.<init>(TheCity.java:89) ~[?:?]
    at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1404) ~[?:?]
```

Can't load into run anymore
