### ISSUE TITLE
Crash on entering the Special Bonfire in todays daily run

### ISSUE THREAD

**Issue by ChristophPech** [The-Evil-Pickle/Replay-the-Spire#111]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at replayTheSpire.patches.ReplayCampButtonsPatch.GetBonfireOptions(ReplayCampButtonsPatch.java:44)
	at replayTheSpire.patches.ReplayCampButtonsPatch.Postfix(ReplayCampButtonsPatch.java:141)
	at com.megacrit.cardcrawl.rooms.CampfireUI.initializeButtons(CampfireUI.java:151)
	at com.megacrit.cardcrawl.rooms.CampfireUI.<init>(CampfireUI.java:59)
	at com.megacrit.cardcrawl.rooms.RestRoom.onPlayerEntry(RestRoom.java:35)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2319)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2183)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2850)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2536)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:877)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)10:29:42.137 INFO helpers.File>

**Comment by The-Evil-Pickle** [comment]
This was caused by use of mods with the beta branch, but has now been fixed
