### ISSUE TITLE
Halts patching after BaseMod 5.12.0 update

### ISSUE THREAD

**Issue by dogoken** [The-Evil-Pickle/Replay-the-Spire#115]
```
ModVersion Info:
 - Java version (1.8.0_131)
 - Slay the Spire (01-23-2019)
 - ModTheSpire (3.8.3)
Mod list:
 - basemod (5.12.0)
 - stslib (1.14.0)
 - ReplayTheSpireMod (1.3.25)

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.MissingParamTypesException: Patch basemod.patches.com.megacrit.cardcrawl.powers.CloneablePowersPatch$SlowPowerPatch
Patching .<ctor>:
Has overloads and no paramtypes defined
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:243)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:269)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:265)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dogoken** [comment]
Fixed in latest Steam Workshop release
