### ISSUE TITLE
Ringing Soul relic possible bug

### ISSUE THREAD

**Issue by Fizz78** [The-Evil-Pickle/Replay-the-Spire#117]
When card reward was chosen, game crashed

Mods used:
ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (01-23-2019)
 - ModTheSpire (3.8.3)
Mod list:
 - basemod (5.12.0)
 - stslib (1.14.0)
 - ReplayTheSpireMod (1.3.25)
 - hubris (0.21.4)
 - coloredmap (2.4.0)
 - infinitespire (0.15.1)
 - SpikesRelics (0.023)
 - relicsorter (1.1.2)
 - conspire (1.5.5)
 - jedi (0.4.3)
 - ShopMod (1.0.3)
 - StrawberrySpire (0.4.3)
 - Halation (0.0.18)
 - TheJungle (1.4.3)
 - Guardian (0.2.5)
 - HighlightPath (0.0.3)
 - beakedthecultist-sts (0.6.3)
 - DeckTracker (0.1.3)

`08:59:36.174 INFO basemod.BaseMod> publishMaxHPChange
Exception: java.util.ConcurrentModificationException
08:59:36.175 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_144]
	at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2646) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
`

**Comment by AvangionQ** [comment]
I'm getting the same problem ... crashes every time, allows me to pick up a card, go to the next battle, repeat the crash again ...
